sudo: required
language: ruby c

matrix:
 include:
    #- os: osx
    #  compiler: clang
    #  osx_image: xcode7.3
    - os: linux
      dist: trusty
      rvm: "2.4"
      compiler: gcc
    - os: linux
      dist: xenial
      rvm: "2.7"
      compiler: clang

before_install:
  - sudo pip install gcovr
  - sudo apt-get update -qq && sudo apt-get install --assume-yes --quiet gcc-multilib && sudo apt-get install -qq gcc-avr binutils-avr avr-libc

install:
  - gem update bundler
  - bundle install

script:
  - bundle exec rake ci
  - mkdir examples/blinky/vendor && cd examples/blinky/vendor && ln -s ../../.. ./ceedling && cd .. && rake module:create[someNewModule] module:destroy[someNewModule] test:all && cd ../..
  - mkdir examples/temp_sensor/vendor && cd examples/temp_sensor/vendor && ln -s ../../.. ./ceedling && cd .. && rake module:create[someNewModule] module:destroy[someNewModule] test:all && cd ../..
